export const MAIN_PAGE_URL = 'main';
export const LOGIN_PAGE_URL = 'login';
export const REGISTER_PAGE_URL = 'register';
export const NOT_FOUND_PAGE_URL = 'not-found';
export const RESET_PASSWORD_PAGE_URL = 'reset-password';
export const USER_EDIT_PAGE_URL = 'account';
export const REDACTOR_TEST_PAGE_URL = 'test';
export const ADD_QUESTIONS = 'questions';
export const RESOLVE_TEST = 'resolve';
export const USER_PAGE = 'main'; //todo: ustwaić odpowiednią ścieżke
