spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: masi.magenda@gmail.com
    password: masi.magenda123
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: "*"
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    url: jdbc:postgresql://212.191.92.88:51530/magenta
    username: magenta
    password: dbpass
  http:
    multipart:
      max-file-size: 11MB
      max-request-size: 11MB
server:
  port: 8080
config:
  security:
    jwt:
      secret: "SecretKey"
      expiration-time: 600_000_000
      refresh-after: 600_000
    password-reset:
      characters: ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789
      length: 6
